import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MainNavBar } from '@/components/NavBar';
import { MainWrapper } from '@/components/wrappers';
import { useMemo } from 'react';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const fields = useMemo(
		() => [
			{ name: 'search', url: '#' },
			{ name: 'Home', url: '/' },
			{ name: 'Login', url: '/login' },
		],
		[]
	);

	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<MainWrapper>
					<MainNavBar fields={fields} />
					{children}
				</MainWrapper>
			</body>
		</html>
	);
}
